### ISSUE TITLE
o__O

### ISSUE THREAD

**Issue by vlfz** [HarumeJs/DiscordBot-Ts#1]
Погоди, то есть ты хочешь сказать, что это бот Ethernal? ([link](https://server-discord.com/728716141802815539))

**Comment by vlfz** [comment]
Пхах, действительно, и зачем я открыл issue
![image](https://user-images.githubusercontent.com/32297717/104833782-19cf2080-58bd-11eb-9466-071c5d1b5870.png)

**Comment by HarumeJs** [comment]
> Погоди, то есть ты хочешь сказать, что это бот Ethernal? ([link](https://server-discord.com/728716141802815539))

Так точно.

**Comment by perssBest** [comment]
da
